version: "3"
services:
    db:
        image: postgres:15
        env_file:
            - .env
        volumes:
            - db_data:/var/lib/postgresql/data

    app:
        build: .
        env_file:
            - .env
        # command: bundle exec rails s -p 3000 -b '0.0.0.0'
        command: bash -c "bundle exec rails db:migrate && bundle exec rails s -p 3000 -b '0.0.0.0'"

        volumes:
            - .:/app
        ports:
            - "3000:3000"
        depends_on:
            - db

volumes:
    db_data:
