services:
    db:
        image: postgres:15
        environment:
            - POSTGRES_DB=budget_db
            - POSTGRES_USER=budget_user
            - POSTGRES_PASSWORD=budget_password
        ports:
            - "5432:5432"

    app:
        build: .
        command: python manage.py runserver 0.0.0.0:8000 # Run Django's dev server
        volumes:
            - .:/app
        ports:
            - "8000:8000"
        depends_on:
            - db
        environment:
            - DEBUG=1
            - DB_NAME=budget_db
            - DB_USER=budget_user
            - DB_PASSWORD=budget_password
            - DB_HOST=db
            - DB_PORT=5432
