version: "3.9"

services:
    web:
        build: .
        command: sh -c "python manage.py makemigrations && python manage.py migrate && gunicorn churugastos.wsgi:application --workers 3 --bind 0.0.0.0:8000"
        # command: gunicorn churugastos.wsgi:application --workers 3 --bind 0.0.0.0:8000
        ports:
            - "8000:8000"
        volumes:
            - .:/app
        environment:
            - DEBUG=${DEBUG}
            - DB_NAME=${DB_NAME}
            - DB_USER=${DB_USER}
            - DB_PASSWORD=${DB_PASSWORD}
            - DB_HOST=${DB_HOST}
            - DB_PORT=${DB_PORT}
        depends_on:
            - db

    db:
        image: postgres:15
        environment:
            POSTGRES_DB: ${DB_NAME}
            POSTGRES_USER: ${DB_USER}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
        volumes:
            - postgres_data:/var/lib/postgresql/data
        ports:
            - "5432:5432"

volumes:
    postgres_data:
