# Generated by Django 5.1.1 on 2024-09-21 12:45
from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_budget_to_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Budget',
        ),
    ]
