# Generated by Django 5.1.1 on 2024-09-22 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_normaluser_timezone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='date',
            new_name='month',
        ),
    ]
