# Generated by Django 5.1.1 on 2024-09-22 12:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_rename_date_expense_month'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='month',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='month',
        ),
        migrations.RemoveField(
            model_name='uniqueexpense',
            name='month',
        ),
        migrations.AddField(
            model_name='category',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='expense',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='uniqueexpense',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
