# Generated by Django 5.1.1 on 2024-09-22 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_cardpayment_creditcard'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardpayment',
            name='end_payment_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cardpayment',
            name='payments_made',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='creditcard',
            name='card_last_4',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
