# Generated by Django 5.1.1 on 2024-09-22 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_cardpayment_end_payment_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardpayment',
            name='next_payment_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
