# Generated by Django 5.1.1 on 2024-09-23 10:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_cardpayment_next_payment_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardpayment',
            name='card_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.creditcard'),
            preserve_default=False,
        ),
    ]
