# Generated by Django 5.1.1 on 2024-09-28 17:05

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_cardpayment_card_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creditcard',
            name='user',
        ),
        migrations.CreateModel(
            name='Credit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
                ('number_of_payments', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('monthly_payment_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payments_made', models.IntegerField(default=0)),
                ('next_payment_date', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='CardPayment',
        ),
        migrations.DeleteModel(
            name='CreditCard',
        ),
    ]
