# Generated by Django 5.1.1 on 2024-09-28 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_remove_creditcard_user_credit_delete_cardpayment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='credit',
            name='is_payment_complete',
            field=models.BooleanField(default=False),
        ),
    ]
