# Generated by Django 5.1.1 on 2024-09-29 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_credit_is_payment_complete'),
    ]

    operations = [
        migrations.AddField(
            model_name='normaluser',
            name='language',
            field=models.CharField(default='en'),
        ),
    ]
