# Generated by Django 5.1.1 on 2024-10-06 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_account_accountbalance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accountbalance',
            old_name='balance',
            new_name='amount',
        ),
    ]
