# Generated by Django 5.1.1 on 2024-10-19 14:29

import django.db.models.deletion
import django.db.models.functions.datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_accountbudget_delete_accountbalance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountbudget',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to='api.account'),
        ),
        migrations.AlterField(
            model_name='accountbudget',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_budgets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='accountbudget',
            constraint=models.UniqueConstraint(condition=models.Q(('date__month', django.db.models.functions.datetime.ExtractMonth('date')), ('date__year', django.db.models.functions.datetime.ExtractYear('date'))), fields=('account',), name='unique_account_budget_per_month'),
        ),
    ]
