# Generated by Django 5.1.1 on 2024-10-19 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_alter_accountbudget_account_alter_accountbudget_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accountbudget',
            old_name='amount',
            new_name='budget',
        ),
    ]
