# Generated by Django 5.1.1 on 2024-10-19 21:38

import django.db.models.deletion
from django.db import migrations, models

def assign_default_account_budget(apps, schema_editor):
    AccountBudget = apps.get_model('api', 'AccountBudget')
    Expense = apps.get_model('api', 'Expense')
    UniqueExpense = apps.get_model('api', 'UniqueExpense')

    # Get the first account budget
    account_budget = AccountBudget.objects.first()

    if account_budget:
        # Assign the first account budget to existing expenses
        for expense in Expense.objects.all():
            expense.account_budget_id = account_budget
            expense.save()

        for unique_expense in UniqueExpense.objects.all():
            unique_expense.account_budget_id = account_budget
            unique_expense.save()

    else:
        # Get or create a default account
        default_account, _ = AccountBudget.objects.create(name='Default Account')

        # Assign the default account to existing expenses
        for expense in Expense.objects.all():
            expense.account_budget_id = default_account
            expense.save()

        for unique_expense in UniqueExpense.objects.all():
            unique_expense.account_budget_id = default_account
            unique_expense.save()

class Migration(migrations.Migration):


    dependencies = [
        ('api', '0022_rename_amount_accountbudget_budget'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='account_budget',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.accountbudget'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='uniqueexpense',
            name='account_budget',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.accountbudget'),
            preserve_default=False,
        ),
    ]
