# Generated by Django 5.1.1 on 2024-10-20 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_remove_accountbudget_unique_account_budget_per_month'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uniqueexpense',
            old_name='name',
            new_name='description',
        ),
    ]
